### ISSUE TITLE
Storyboards

### ISSUE THREAD

**Issue by ghost** [TimOliver/TOSplitViewController#2]
Is there any chance this will be made storyboard compatible so I won't have to initialize it in AppDelegate programmatically?

**Comment by TimOliver** [comment]
@thederekkaplan Sorry for the delay!

That's a great idea! Um, I'm not sure how feasible it is though since I've never tried making a container view controller work in IB before.

If anyone wants to file a PR, please do!

**Comment by mohammadnt** [comment]
you can do it , by overriding awakeFromNib in TOSplitViewController like below :

```
override func awakeFromNib() {
        let storyboard = self.storyboard!
        let mainController = storyboard.instantiateViewController(identifier: "mastervc")
        let primaryNavController = UINavigationController.init(rootViewController: mainController)
        let secondaryController = storyboard.instantiateViewController(identifier: "detailvc")
        let secondaryNavController = UINavigationController.init(rootViewController: secondaryController)
        self.viewControllers = [primaryNavController,secondaryNavController]
        self.delegate = self
    }
```

**Comment by TimOliver** [comment]
Oh brilliant! I had no idea you could do it that way! Thank you so much! :D

I’d say this solves the issue. Closing it off now. :)
